# Generated by Django 4.1.7 on 2023-03-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productdescription', models.CharField(max_length=200)),
                ('productprice', models.FloatField(max_length=50)),
            ],
        ),
    ]
