# Generated by Django 4.1.7 on 2023-03-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationname', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productlocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.location'),
        ),
    ]
